spring:
  application:
    name: LibraryManagement
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
  
  lifecycle:
    timeout-per-shutdown-phase: 30s
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  shutdown: graceful
  tomcat:
    connection-timeout: 20s
    keep-alive-timeout: 20s

logging:
  level:
    com.library: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always