# Library Management System - Flyway Configuration Profile
# Use this profile when you want to use Flyway migrations instead of JPA auto-generation

spring:
  application:
    name: LibraryManagement
  
  # JPA Configuration for Flyway
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from create-drop to validate for Flyway
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    ignore-migration-patterns:
      - "*:pending"
    placeholder-replacement: false
    
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: ${DB_USERNAME:library_user}
    password: ${DB_PASSWORD:library_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false
      connection-test-query: SELECT 1
      pool-name: LibraryHikariPool
  
  # Lifecycle configuration
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  compression:
    enabled: true
  http2:
    enabled: true

# Logging configuration
logging:
  level:
    com.library: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/library-management-flyway.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,flyway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    flyway:
      enabled: true
  info:
    env:
      enabled: true
  health:
    diskspace:
      enabled: true