spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:library_user}
    password: ${DB_PASSWORD:library_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
        connection:
          provider_disables_autocommit: true
  
  h2:
    console:
      enabled: false
  
  lifecycle:
    timeout-per-shutdown-phase: 60s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  tomcat:
    connection-timeout: 30s
    keep-alive-timeout: 30s
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    com.library: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    root: WARN
  file:
    name: logs/library-management.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
  server:
    port: ${MANAGEMENT_PORT:8081}
    ssl:
      enabled: false