spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:library_user}
    password: ${DB_PASSWORD:library_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
        connection:
          provider_disables_autocommit: true
  
  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.library: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    root: WARN
  file:
    name: logs/library-management.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized